import './globals.css';
import { Inter } from 'next/font/google';

import TopLayout from './topLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Lawyer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopLayout>{children}</TopLayout>
      </body>
    </html>
  );
}
